Auth controller
TNTrol/projectForRC pull request #1
Opened 2021-11-30 07:18 UTC by TNTrol

2021-11-30 07:56 UTC, Boykooo requested changes

2021-11-30 07:56 UTC, Boykooo commented on pom.xml
> +            <version>42.2.24</version>
Версия вроде бы не нужна, подтягивается из пэрента

2021-11-30 07:56 UTC, Boykooo commented on pom.xml
> +            <version>4.11</version>
Тут вроде бы тоже не нужна

2021-11-30 07:56 UTC, Boykooo commented on scripts/script.sql
> +    name CHARACTER VARYING(30) NOT NULL
CHARACTER VARYING(30) -> VARCHAR (30)

2021-11-30 07:56 UTC, Boykooo commented on src/main/java/ru/redcollar/store/Main.java
> +//    @Bean
Лишний код не держим, удаляем
Если понадобиться - то смотрим по истории гита

2021-11-30 07:56 UTC, Boykooo commented on src/main/java/ru/redcollar/store/controller/AuthController.java
> +        catch (UserExistsException e)
Никаких обработчиков в контроллерах, нужно перенсти в сервисы. Но уже говорил

2021-11-30 07:56 UTC, Boykooo commented on src/main/java/ru/redcollar/store/controller/AuthController.java
> +@Controller
Почитай, чем отличается Controller и RestController
И надо понять, чем именно пользоваться

2021-11-30 07:56 UTC, Boykooo commented on src/main/java/ru/redcollar/store/domain/entity/Role.java
> +    @Column(name = "id")
На айдишник Column не пишут особо, потому что он зачастую совпадает со названием колонки в  БД. И зачастую это просто 'id'

2021-11-30 07:56 UTC, Boykooo commented on src/main/java/ru/redcollar/store/exceptions/BadLoginException.java
> +public class BadLoginException extends Exception{
Почитай про отличие Exception и RuntimeException

2021-11-30 07:56 UTC, Boykooo commented on src/main/java/ru/redcollar/store/exceptions/BadLoginException.java
> +public class BadLoginException extends Exception{
И надо понять, какой вариант будет получше

2021-11-30 07:56 UTC, Boykooo commented on src/main/java/ru/redcollar/store/repository/UserRepository.java
> +@Repository
Аннотация необязательна
Потому что ты наследуешься от JpaRepository - спринг это увидит и создаст бин

2021-11-30 07:56 UTC, Boykooo commented on src/main/java/ru/redcollar/store/service/AuthService.java
> +    @Autowired
Инжект через поле довольно устаревшая штука
На данный момент лаконичнее использовать инжект через конструктор
Когда ты передаешь все бины в конструкторе и потом их присваиваешь своим локальным переменным
Т.е. вместо автовайреда - суем в конструктор, а в нем присваиваем roleService'у и userService'у

И после этого еще немного магии. Т.к. мы передаем все бины в конструктор для инициализации, мы можем их сделать final полями. Т.е. инициализироваться они будут один раз. И далее, с помощью ломбока и аннотации RequiredArgsContructor мы сгенерируем конструктор из final полей

Тем самым мы мы просто Определяем файнал бины, ломбоком генерим конструктор, и происходит автовайринг. 
Кода меньше, читается проще

2021-11-30 07:56 UTC, Boykooo commented on src/main/java/ru/redcollar/store/service/AuthService.java
> +        user.setPassword(password);
При сохранении пароля использовать BCryptPasswordEncoder, использовать бином

2021-11-30 07:56 UTC, Boykooo commented on src/main/java/ru/redcollar/store/service/AuthService.java
> +        if(user == null || !user.getPassword().equals(password))
При сравнении паролей так же использовать BCryptPasswordEncoder

2021-11-30 07:56 UTC, Boykooo commented on src/main/java/ru/redcollar/store/service/AuthService.java
> +        if(user == null || !user.getPassword().equals(password))
С клиента пароль всегда летит в чистом виде (в нашем случае)

2021-11-30 09:08 UTC, TNTrol commented on pom.xml
> +            <version>42.2.24</version>
Исправил

2021-11-30 09:08 UTC, TNTrol commented on pom.xml
> +            <version>4.11</version>
Исправил

2021-11-30 09:08 UTC, TNTrol commented on scripts/script.sql
> +    name CHARACTER VARYING(30) NOT NULL
Исправил

2021-11-30 09:09 UTC, TNTrol commented on src/main/java/ru/redcollar/store/Main.java
> +//    @Bean
Испавил

2021-11-30 09:09 UTC, TNTrol commented on src/main/java/ru/redcollar/store/controller/AuthController.java
> +        catch (UserExistsException e)
Удалил обработку ошибок из контроллера

2021-11-30 09:10 UTC, TNTrol commented on src/main/java/ru/redcollar/store/domain/entity/Role.java
> +    @Column(name = "id")
Удалил

2021-11-30 09:43 UTC, TNTrol commented on src/main/java/ru/redcollar/store/service/AuthService.java
> +        if(user == null || !user.getPassword().equals(password))
Добавил

2021-11-30 09:43 UTC, TNTrol commented on src/main/java/ru/redcollar/store/service/AuthService.java
> +        user.setPassword(password);
Добавил

2021-11-30 09:43 UTC, TNTrol commented on src/main/java/ru/redcollar/store/service/AuthService.java
> +    @Autowired
Исправил

2021-12-02 10:38 UTC, Boykooo commented on src/main/java/ru/redcollar/store/component/JwtConverter.java
> +            Integer id = (Integer) body.get("id");
Сразу в лонг нельзя кастить?

2021-12-02 10:38 UTC, Boykooo commented on src/main/java/ru/redcollar/store/config/SecurityConfig.java
> +                .antMatchers("/registration").permitAll()
Можно указать через запятую эндпойнты

2021-12-02 10:38 UTC, Boykooo commented on src/main/java/ru/redcollar/store/controller/AuthController.java
> +    @GetMapping("/showMe")
стилистика названия эндпойнтов - "show-me" - Слова разделяются дефисом и пишутся с маленькой буквы
Вообще везде все делают по-разному, но этот вариант считается лучшим

2021-12-02 10:38 UTC, Boykooo commented on src/main/java/ru/redcollar/store/controller/AuthController.java
> +        return new ResponseEntity<>(key, HttpStatus.OK);
можно просто return ResponseEntity.ok(key)

2021-12-02 10:38 UTC, Boykooo commented on src/main/java/ru/redcollar/store/controller/AuthController.java
> +        return authService.getUser((String) authentication.getCredentials());
не надо принимать Authentication в контроллере - перенеси логику в сервис. Там достань из SecurityContextHolder его
И респонс из контроллера сделай через ResponseEntity

2021-12-02 10:38 UTC, Boykooo commented on src/main/java/ru/redcollar/store/domain/entity/User.java
> +
Лишняя пустая строчка

2021-12-02 10:38 UTC, Boykooo commented on src/main/java/ru/redcollar/store/exceptions/BadLoginException.java
> +public class BadLoginException extends RuntimeException{
Нужен пробел после RuntimeException

2021-12-02 10:38 UTC, Boykooo commented on src/main/java/ru/redcollar/store/exceptions/UserExistsException.java
> +public class UserExistsException extends RuntimeException{
Нужен пробел после RuntimeException

2021-12-02 10:38 UTC, Boykooo commented on src/main/java/ru/redcollar/store/component/JwtConverter.java
> +    @Value("${jwt.secret}")
Нужен отступ в виде пустой линии

2021-12-02 11:21 UTC, TNTrol commented on src/main/java/ru/redcollar/store/controller/AuthController.java
> +        return authService.getUser((String) authentication.getCredentials());
https://github.com/TNTrol/projectForRC/blob/250cc2f5d93dc199256779f5a1e1349d715469e5/src/main/java/ru/redcollar/store/controller/AuthController.java#L35

2021-12-02 11:21 UTC, TNTrol commented on src/main/java/ru/redcollar/store/domain/entity/User.java
> +
Исправил

2021-12-02 11:22 UTC, TNTrol commented on src/main/java/ru/redcollar/store/component/JwtConverter.java
> +            Integer id = (Integer) body.get("id");
Исправлю, но если заменить интежер заменить на лонг, то ошибка при конвертации

2021-12-02 11:23 UTC, TNTrol commented on src/main/java/ru/redcollar/store/controller/AuthController.java
> +    @GetMapping("/showMe")
https://github.com/TNTrol/projectForRC/blob/250cc2f5d93dc199256779f5a1e1349d715469e5/src/main/java/ru/redcollar/store/controller/AuthController.java#L34

2021-12-02 11:23 UTC, TNTrol commented on src/main/java/ru/redcollar/store/controller/AuthController.java
> +        return new ResponseEntity<>(key, HttpStatus.OK);
https://github.com/TNTrol/projectForRC/blob/250cc2f5d93dc199256779f5a1e1349d715469e5/src/main/java/ru/redcollar/store/controller/AuthController.java#L25

2021-12-02 11:23 UTC, TNTrol commented on src/main/java/ru/redcollar/store/exceptions/BadLoginException.java
> +public class BadLoginException extends RuntimeException{
Добавил

2021-12-02 11:24 UTC, TNTrol commented on src/main/java/ru/redcollar/store/component/JwtConverter.java
> +    @Value("${jwt.secret}")
Добавил

2021-12-02 11:36 UTC, merged